### ISSUE TITLE
Revise `versioning_alter_history` modes (part 2)

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#353]
## 1. For ERROR mode
Fail **only** when history is non empty with following error (`ER_VERS_ALTER_NOT_ALLOWED`):
```
History is not empty for `%s.%s`. Change `versioning_alter_history` to proceed with ALTER.
```

### Handle IB inplace for alter_history drop mode 
When `versioning_alter_history=DROP` inplace algorithm must avoid data rebuild and execute an extra step of dropping the history.

### `UNIQUE NOT NULL` works
Make sure `ADD COLUMN UNIQUE NOT NULL` works. Currently it fails with `ER_UNSUPPORTED_EXTENSION`.

### Notes
@vuvova

> On Nov 24, Sergei Golubchik wrote:
> On Nov 24, Alexey Midenkov wrote:
> >
> > In 11.11 <add column definition>, 11.12 <alter column definition>, 11.23
> > <drop column definition> in Syntax rules it says:
> >
> > "T shall not be a referenceable table or a system-versioned table."
> >
> > AFAIU this means that T is not system-versioned at the moment of ALTER
> > start.
>
> Agree, you're right.
>
> Then let's have two modes ERROR (default) and KEEP.
> And have DROP/etc for the future.
>
> > DROP is dangerous operation: it is not expected to lose data by running
> > ALTER ADD COLUMN. That's why I'd not recommend to make it default.

Monty wants to be able to specify DROP behavior as a part of ALTER
TABLE. Given that, and taking into account that DROP, you're right, is a
dangerous operation, let's not have DROP mode at all, but instead
support

   ALTER TABLE ... DROP HISTORY

Like in

   ALTER TABLE .... ADD COLUMN x INT, DROP HISTORY;

Not necessarily with this syntax (may be FORGET HISTORY or TRUNCATE
VERSIONING or something), and not in 10.3.3, of course. Sometime in the
future.

What do you think?

**Comment by dr-m** [comment]
I prefer to have as few global or session parameters as possible. Hence, I prefer the concept of `ALTER TABLE…DROP HISTORY` to some global variable that would affect the behaviour of `ALTER TABLE`.

I have a minor objection about the syntax: Currently, the following two statements are equivalent:
```sql
ALTER TABLE t DROP history;
ALTER TABLE t DROP COLUMN history;
```
Unless this suggested syntax is part of some standard, I would prefer some different syntax that cannot break existing applications. The word `history` was not a reserved word in MariaDB, and the word is rather generic, so users could have columns by that name. `TRUNCATE VERSIONING` would be nicer, because it is reusing already reserved words.

In a table-rebuilding `ALTER`, the history can be dropped at no additional cost, by just omitting the historical rows in `row_merge_read_clustered_index()`.

For any other form of `ALTER TABLE…ALGORITHM=INPLACE`, removing the historical rows would have to be an additional step. I think that it should be done with appropriate undo logging, in `ha_innobase::inplace_alter_table()`. It will be a bit tricky when the operation includes any creation of secondary indexes. If it does, then we’ll have to ignore the historical records both in row0merge.cc and row0log.cc (do not write `online_log` for operations on historical rows). The test innodb.innodb-index-online should be extended (possibly used as a basis of a different test file) to cover this.

**Comment by vuvova** [comment]
Yes, I'd also prefer `ALTER TABLE ... TRUNCATE VERSIONING`
